### ISSUE TITLE
3.0/common is broken?

### ISSUE THREAD

**Issue by MightyM17** [Unlegacy-Android/android_kernel_ti_omap4#3]
I am trying to build AEX nougat (for espresso) with the 3.0/common kernel and there seem to be a lot of errors? Is 3.0/common not working with nougat? Should i try other branches?
Please reply

**Comment by andi34** [comment]
It is working on N fine. Maybe try a different Toolchain or Check Rom specific needs

**Comment by andi34** [comment]
For example check the custom.mk files:
https://github.com/LineageOS/android_device_samsung_espressowifi

**Comment by MightyM17** [comment]
I dunno i cant even build LineageOS oreo with it

**Comment by andi34** [comment]
You were asking about Nougat, lol. Was meant as example as different Roms need different settings sometimes.

**Comment by andi34** [comment]
And maybe also take a look if you have all bits for the new ddk https://gerrit.unlegacy-android.org/q/topic:%22omap-ddk-1.14%22+(status:open%20OR%20status:merged)

**Comment by MightyM17** [comment]
> You were asking about Nougat, lol. Was meant as example as different Roms need different settings sometimes.

I tried AEX nougat it seems that the rom is broken so i moved to Lineage Oreo but it gives another error
